name: dart_nvim_api
description: A Neovim API for Dart allowing for communication between a Neovim instance and a Dart program. Can be used for creating Neovim plugins, Neovim frontend GUIs, etc.
version: 0.3.0
homepage: https://github.com/smolck/dart-nvim-api

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  msgpack_dart: ^1.0.0
  meta: ^1.1.7

dev_dependencies:
  dart_style:
  code_builder:
  test:
